language: cpp

addons:
  apt:
    packages:
    - gcc-4.8
    - g++-4.8

before_script: cp makefiles/makefile.defs.linux.alsa ./makefile.defs && mv external/portaudio external/portaudio2014 && mv external/portaudio2007 external/portaudio
script: make
